version: "3.9"

services:
  sentiment-app:
    container_name: sentiment-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000/tcp
    environment:
      - TZ=Asia/Kolkata
      - PORT=8000
      - WORKERS=2